stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --cache=true --destination eu.gcr.io/itp-gce-registry/helm-sops:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG